<a href="https://colab.research.google.com/github/manny-uncharted/pytorch-projects-learnings/blob/main/Pytorch_recap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

# Initializing tensors

In [ ]:
## Initializing Tensors
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32,
                         device=device, requires_grad=True)

print(my_tensor)

# Attributes of tensor
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])
True


In [ ]:
# Other common initialization methods
x = torch.empty(size = (3, 3)) # creates a random uninitialized tensors of size 3 * 3
print(x)
y = torch.zeros((3, 3)) # creates a 3 * 3 matrix of zeros
print(y)
z = torch.rand((3, 3)) # creates a 3 * 3 from a uniform distribution with values between zeros and one
print(z)

w = torch.ones((3, 3)) # creates a 3 * 3 matrix of ones
print(w)

v = torch.eye(5, 5) # creates an identity matrix with % * 5 dimensions
print(v)

tensor([[-3.5746e-14,  4.5759e-41,  1.3173e-34],
        [ 0.0000e+00,  1.0000e+00,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00,  6.7262e-44]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.1582, 0.2864, 0.1346],
        [0.5093, 0.3991, 0.4289],
        [0.5821, 0.8192, 0.5512]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
x = torch.arange(start=0, end=5, step=1) 
print(x)

y = torch.linspace(start=0.1, end=1, steps=10)
print(y)

tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [ ]:
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
print(x)

y = torch.empty(size=(1, 5)).uniform_(0, 1)
print(y)

tensor([[ 0.6070, -1.7468,  0.1833, -0.0626,  1.5187]])
tensor([[0.6353, 0.1593, 0.0898, 0.4705, 0.2297]])


In [ ]:
x = torch.diag(torch.ones(3)) # creates a diagonal 3 * 3 matrix
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## Converting tensors to other types

In [ ]:
# Initializing and converting tensors from one type to another (int, float, double)

tensor = torch.arange(4)
print(tensor.bool()) # boolean True/False
print(tensor.short()) # int16
print(tensor.long()) #int64 (Important)
print(tensor.half()) # float16
print(tensor.float()) # float32 (Important)
print(tensor.double()) # float64

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [ ]:
# Numpy Array to Tensor conversion and vice-versa

import numpy as np

np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
np_array_back = tensor.numpy()

# Tensor Math & Comparison Operations

In [8]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])


# Addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)
print(z1)
z2 = torch.add(x, y)
print(z2)
z = x + y
print(z)


# Subtraction
z = x - y

# Division
z = torch.true_divide(x, y) # performs element-wise division if their size are same

# inplace operations
t = torch.zeros(3)
t.add_(x)
t += x # t = t + x

# Exponentiation
z = x.pow(2)
print(z)

z = x ** 2


# Simple Comparison
z = x > 0
z = x < 0

# Matrix multiplication
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2) # 2x3 matrix
x3 = x1.mm(x2)


# matrix exponentiation
matrix_exp = torch.rand(5, 5)
print(matrix_exp.matrix_power(3))


# Element-wise multiplication
z = x * y
print(z)

# dot product 
z = torch.dot(x, y)
print(z)

# Batch Matrix Multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)
print(out_bmm)

tensor([5., 7., 9.])
tensor([5, 7, 9])
tensor([5, 7, 9])
tensor([1, 4, 9])
tensor([[2.0914, 1.6948, 2.4028, 0.6488, 2.6376],
        [2.5472, 2.3342, 3.2217, 0.8609, 3.6544],
        [3.2233, 2.7068, 3.8097, 1.0128, 4.1922],
        [2.5747, 2.0244, 2.8953, 0.7851, 3.1073],
        [4.1757, 3.5411, 4.9724, 1.3358, 5.5001]])
tensor([ 4, 10, 18])
tensor(32)
tensor([[[5.3617, 5.3127, 4.8557,  ..., 4.8944, 3.9599, 5.5028],
         [4.9910, 4.7527, 4.3590,  ..., 4.7295, 4.0976, 4.5488],
         [4.6596, 4.5119, 3.8936,  ..., 4.0102, 4.4042, 4.9218],
         ...,
         [5.7613, 5.1051, 4.8093,  ..., 4.5556, 5.6012, 5.3501],
         [7.2698, 6.7666, 6.0463,  ..., 5.9543, 5.4576, 7.0971],
         [6.5333, 6.3881, 5.8086,  ..., 5.1771, 5.0570, 6.1548]],

        [[4.9606, 4.0065, 4.0986,  ..., 4.1182, 4.3984, 4.3587],
         [5.4848, 4.3625, 3.6621,  ..., 3.9034, 5.6189, 4.4960],
         [4.3939, 3.6843, 4.1462,  ..., 3.6537, 4.3550, 4.0922],
         ...,
         [5.2752, 4.6105, 4

In [9]:
# Example of Broadcasting: Automatically expands unequal matrices so that they match
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))

z = x1 - x2
z = x1 ** x2
print(z)

tensor([[0.0315, 0.9373, 0.7791, 0.9290, 0.8424],
        [0.8208, 0.9875, 0.7648, 0.8564, 0.5132],
        [0.4989, 0.9645, 0.8303, 0.7341, 0.8150],
        [0.9927, 0.9680, 0.6033, 0.7949, 0.2234],
        [0.7914, 0.9048, 0.5890, 0.1702, 0.6337]])


In [16]:
# Other useful tensor operations

sum_x = torch.sum(x, dim=0)
values, indices = torch.max(x, dim=0)
values, indices = torch.min(x, dim=0)
abs_x = torch.abs(x)
z = torch.argmax(x, dim=0)
z = torch.argmin(x, dim=0)

mean_x = torch.mean(x.float(), dim=0)
z = torch.eq(x, y)
print(z)

sorted_y, indices = torch.sort(y, dim=0, descending=False)

z = torch.clamp(x, min=0)
print(z)

w = torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool)
z = torch.any(w)
z = torch.all(w)
print(z)

tensor([False, False, False])
tensor([1, 2, 3])
tensor(False)


# Tensor Indexing

In [25]:
batch_size = 10 
features = 25

x = torch.rand((batch_size, features))

# Getting the features of the first example
print(x[0].shape) # x[0, :]

# Getting the first feature of all our samples
print(x[:, 0].shape)

# Get the 3rd example in the batch and the first 10 features
print(x[2, 0:10]) 

x[0, 0] = 100

# Fancy Indexing
x = torch.arange(10)
indices = [2, 5, 8]
print(x[indices])

x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
print(x[rows, cols])

# More advanced indexing
x = torch.arange(10)
print(x[(x < 2) & (x > 8)])
print(x[x.remainder(2) == 0])


# Useful Operations
print(torch.where(x > 5, x, x * 2))
print(torch.tensor([0, 0, 1, 2, 3, 4]).unique())
print(x.ndimension())
print(x.numel())

torch.Size([25])
torch.Size([10])
tensor([0.5295, 0.7572, 0.5522, 0.2537, 0.1381, 0.6062, 0.0043, 0.0474, 0.6311,
        0.6092])
tensor([2, 5, 8])
tensor([0.7601, 0.2324])
tensor([], dtype=torch.int64)
tensor([0, 2, 4, 6, 8])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


# Tensor Reshaping

In [33]:
x = torch.arange(9)
x_3x3 = x.view(3, 3)
print(x_3x3)
x_3x3 = x.reshape(3, 3)


y = x_3x3.t()
print(y)
print(y.contiguous().view(9))

x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
print(torch.cat((x1, x2), dim=0).shape)
print(torch.cat((x1, x2), dim=1).shape)

z = x1.view(-1)
print(z.shape)

batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)

z = x.permute(0, 2, 1)
print(z.shape)

x = torch.arange(10)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

x = torch.arange(10).unsqueeze(0).unsqueeze(1) # 1x1x10
z = x.squeeze(1)
print(z.shape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
torch.Size([4, 5])
torch.Size([2, 10])
torch.Size([10])
torch.Size([64, 10])
torch.Size([64, 5, 2])
torch.Size([1, 10])
torch.Size([10, 1])
torch.Size([1, 10])
