<a href="https://colab.research.google.com/github/manny-uncharted/pytorch-projects-learnings/blob/main/Pytorch_recap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Initializing tensors

In [5]:
## Initializing Tensors
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32,
                         device=device, requires_grad=True)

print(my_tensor)

# Attributes of tensor
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])
True


In [8]:
# Other common initialization methods
x = torch.empty(size = (3, 3)) # creates a random uninitialized tensors of size 3 * 3
print(x)
y = torch.zeros((3, 3)) # creates a 3 * 3 matrix of zeros
print(y)
z = torch.rand((3, 3)) # creates a 3 * 3 from a uniform distribution with values between zeros and one
print(z)

w = torch.ones((3, 3)) # creates a 3 * 3 matrix of ones
print(w)

v = torch.eye(5, 5) # creates an identity matrix with % * 5 dimensions
print(v)

tensor([[-3.5746e-14,  4.5759e-41,  1.3173e-34],
        [ 0.0000e+00,  1.0000e+00,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00,  6.7262e-44]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.1582, 0.2864, 0.1346],
        [0.5093, 0.3991, 0.4289],
        [0.5821, 0.8192, 0.5512]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [10]:
x = torch.arange(start=0, end=5, step=1) 
print(x)

y = torch.linspace(start=0.1, end=1, steps=10)
print(y)

tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [11]:
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
print(x)

y = torch.empty(size=(1, 5)).uniform_(0, 1)
print(y)

tensor([[ 0.6070, -1.7468,  0.1833, -0.0626,  1.5187]])
tensor([[0.6353, 0.1593, 0.0898, 0.4705, 0.2297]])


In [12]:
x = torch.diag(torch.ones(3)) # creates a diagonal 3 * 3 matrix
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## Converting tensors to other types

In [16]:
# Initializing and converting tensors from one type to another (int, float, double)

tensor = torch.arange(4)
print(tensor.bool()) # boolean True/False
print(tensor.short()) # int16
print(tensor.long()) #int64 (Important)
print(tensor.half()) # float16
print(tensor.float()) # float32 (Important)
print(tensor.double()) # float64

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [17]:
# Numpy Array to Tensor conversion and vice-versa

import numpy as np

np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
np_array_back = tensor.numpy()

# Tensor Math & Comparison Operations